<?php
$vi_add = [
    'about_us' => 'Về Chúng Tôi',
    'about_us_sub' => 'Câu chuyện của Đắk Lắk Travel AI',
    'about_p1' => 'Đắk Lắk Travel AI là nền tảng du lịch tiên phong...',
    'about_p2' => 'Chúng tôi kết hợp trí tuệ nhân tạo...',
    'feature_iti' => 'Lịch trình thông minh',
    'feature_iti_desc' => 'Tự động tạo lịch trình cá nhân hóa',
    'feature_chat' => 'Trợ lý AI 24/7',
    'feature_chat_desc' => 'Luôn sẵn sàng giải đáp mọi thắc mắc',
    'feature_local' => 'Trải nghiệm bản địa',
    'feature_local_desc' => 'Đề xuất những địa điểm đậm chất địa phương',
    'comments_count' => 'bình luận',
    'share_thought' => 'Chia sẻ suy nghĩ của bạn',
    'send_comment' => 'Gửi bình luận',
    'login_to_comment' => 'Đăng nhập để bình luận',
    'view_all_articles' => 'Xem tất cả bài viết',
    'chatbot_title' => 'Trợ Lý AI',
    'chatbot_sub' => 'Hỏi đáp về du lịch Đắk Lắk',
    'type_msg' => 'Nhập tin nhắn...',
    'send_btn' => 'Gửi',
    'contact_us' => 'Liên Hệ',
    'contact_sub' => 'Hãy để lại lời nhắn cho chúng tôi',
    'contact_info' => 'Thông tin liên hệ',
    'send_msg' => 'Gửi tin nhắn',
    'email_label' => 'Địa chỉ Email',
    'subject_label' => 'Chủ đề',
    'message_label' => 'Nội dung',
    'remove_wishlist' => 'Bỏ lưu',
    'save_wishlist' => 'Lưu điểm đến',
    'avg_visit_time' => 'Thời gian tham quan trung bình',
    'price_level' => 'Mức chi phí',
    'about_dest' => 'Giới thiệu điểm đến',
    'location' => 'Vị trí',
    'reviews_tab' => 'Đánh giá',
    'write_review' => 'Viết đánh giá của bạn',
    'send_review' => 'Gửi đánh giá',
    'login_to_review' => 'Đăng nhập để đánh giá',
    'dest_title' => 'Khám Phá Điểm Đến',
    'dest_sub' => 'Vẻ đẹp hùng vĩ của Đắk Lắk',
    'all_categories' => 'Tất cả danh mục',
    'search_dest' => 'Tìm điểm đến...',
    'search_keyword' => 'Từ khóa tìm kiếm',
    'filter_price' => 'Lọc theo giá',
    'all_prices' => 'Mọi mức giá',
    'filter_rating' => 'Lọc theo đánh giá',
    'all_ratings' => 'Mọi đánh giá',
    'clear_filter' => 'Xóa bộ lọc',
    'no_dest' => 'Không tìm thấy điểm đến nào.',
    'forgot_password' => 'Quên mật khẩu',
    'forgot_password_sub' => 'Lấy lại mật khẩu của bạn',
    'back_to_login' => 'Quay lại đăng nhập',
    'back_to_profile' => 'Quay lại hồ sơ',
    'export_pdf' => 'Xuất PDF',
    'total_distance' => 'Tổng khoảng cách',
    'travel_time' => 'Thời gian di chuyển',
    'how_many_days' => 'Bao nhiêu ngày?',
    'route_details' => 'Chi tiết tuyến đường',
    'login_title' => 'Đăng Nhập',
    'login_sub' => 'Chào mừng bạn quay lại',
    'map_title' => 'Bản Đồ Đắk Lắk',
    'map_sub_1' => 'Khám phá các điểm đến',
    'map_sub_2' => 'trên bản đồ tương tác',
    'register_title' => 'Đăng Ký',
    'register_sub' => 'Tạo tài khoản mới',
    'password_label' => 'Mật khẩu',
    'repassword_label' => 'Nhập lại mật khẩu',
    'has_account' => 'Đã có tài khoản?',
    'login_now' => 'Đăng nhập ngay',
    'reset_password' => 'Đặt Lại Mật Khẩu',
    'go_to_login' => 'Đi tới đăng nhập',
    'update_password' => 'Cập nhật mật khẩu',
    'safety_title' => 'Cẩm Nang An Toàn',
    'safety_sub' => 'Thông tin cần biết khi du lịch Đắk Lắk',
    'weather_sub' => 'Đặc điểm thời tiết',
    'rainy_season' => 'Mùa mưa (Tháng 5 - Tháng 10)',
    'dry_season' => 'Mùa khô (Tháng 11 - Tháng 4)',
    'emergency_title' => 'Liên Hệ Khẩn Cấp',
    'emergency_sub' => 'Các số điện thoại cần thiết',
    'terrain_title' => 'Địa Hình',
    'terrain_sub' => 'Đặc điểm địa hình cần lưu ý',
    'season_title' => 'Mùa du lịch',
    'invalid_verify_link' => 'Đường dẫn xác thực không hợp lệ',
    'verify_success' => 'Xác thực tài khoản thành công',
    'footer_text' => 'Bản quyền thuộc về biệt đội Báo Đốm',
];

$en_add = [
    'about_us' => 'About Us',
    'about_us_sub' => 'The story of Dak Lak Travel AI',
    'about_p1' => 'Dak Lak Travel AI is a pioneering travel platform...',
    'about_p2' => 'We combine artificial intelligence...',
    'feature_iti' => 'Smart Itinerary',
    'feature_iti_desc' => 'Auto-generate personalized itineraries',
    'feature_chat' => '24/7 AI Assistant',
    'feature_chat_desc' => 'Always ready to answer your questions',
    'feature_local' => 'Local Experience',
    'feature_local_desc' => 'Recommend authentic local spots',
    'comments_count' => 'comments',
    'share_thought' => 'Share your thoughts',
    'send_comment' => 'Send Comment',
    'login_to_comment' => 'Login to comment',
    'view_all_articles' => 'View all articles',
    'chatbot_title' => 'AI Assistant',
    'chatbot_sub' => 'Ask anything about Dak Lak travel',
    'type_msg' => 'Type a message...',
    'send_btn' => 'Send',
    'contact_us' => 'Contact Us',
    'contact_sub' => 'Leave us a message',
    'contact_info' => 'Contact Information',
    'send_msg' => 'Send Message',
    'email_label' => 'Email Address',
    'subject_label' => 'Subject',
    'message_label' => 'Message',
    'remove_wishlist' => 'Remove from Saved',
    'save_wishlist' => 'Save Destination',
    'avg_visit_time' => 'Avg. Visit Time',
    'price_level' => 'Price Level',
    'about_dest' => 'About Destination',
    'location' => 'Location',
    'reviews_tab' => 'Reviews',
    'write_review' => 'Write a review',
    'send_review' => 'Submit Review',
    'login_to_review' => 'Login to review',
    'dest_title' => 'Explore Destinations',
    'dest_sub' => 'The majestic beauty of Dak Lak',
    'all_categories' => 'All Categories',
    'search_dest' => 'Search destinations...',
    'search_keyword' => 'Search keyword',
    'filter_price' => 'Filter by price',
    'all_prices' => 'All prices',
    'filter_rating' => 'Filter by rating',
    'all_ratings' => 'All ratings',
    'clear_filter' => 'Clear Filters',
    'no_dest' => 'No destinations found.',
    'forgot_password' => 'Forgot Password',
    'forgot_password_sub' => 'Recover your password',
    'back_to_login' => 'Back to Login',
    'back_to_profile' => 'Back to Profile',
    'export_pdf' => 'Export PDF',
    'total_distance' => 'Total Distance',
    'travel_time' => 'Travel Time',
    'how_many_days' => 'How many days?',
    'route_details' => 'Route Details',
    'login_title' => 'Login',
    'login_sub' => 'Welcome back',
    'map_title' => 'Dak Lak Map',
    'map_sub_1' => 'Explore destinations',
    'map_sub_2' => 'on the interactive map',
    'register_title' => 'Register',
    'register_sub' => 'Create a new account',
    'password_label' => 'Password',
    'repassword_label' => 'Confirm Password',
    'has_account' => 'Already have an account?',
    'login_now' => 'Login now',
    'reset_password' => 'Reset Password',
    'go_to_login' => 'Go to Login',
    'update_password' => 'Update Password',
    'safety_title' => 'Safety Guide',
    'safety_sub' => 'Things to know when traveling to Dak Lak',
    'weather_sub' => 'Weather characteristics',
    'rainy_season' => 'Rainy Season (May - Oct)',
    'dry_season' => 'Dry Season (Nov - Apr)',
    'emergency_title' => 'Emergency Contacts',
    'emergency_sub' => 'Important phone numbers',
    'terrain_title' => 'Terrain',
    'terrain_sub' => 'Terrain characteristics to note',
    'season_title' => 'Travel Season',
    'invalid_verify_link' => 'Invalid verification link',
    'verify_success' => 'Account verified successfully',
    'footer_text' => 'Copyright by Biệt đội Báo Đốm',
];

function appendToFile($file, $arr) {
    $content = file_get_contents($file);
    $content = rtrim($content);
    if (str_ends_with($content, '];')) {
        $content = substr($content, 0, -2);
    }
    $content = rtrim($content);
    if (str_ends_with($content, ',')) {
        $content .= "\n";
    } else {
        $content .= ",\n";
    }
    foreach ($arr as $k => $v) {
        $content .= "    '$k' => '" . addslashes($v) . "',\n";
    }
    $content .= "];\n";
    file_put_contents($file, $content);
}

appendToFile('C:\xampp\htdocs\travel_daklak\main\includes\lang_vi.php', $vi_add);
appendToFile('C:\xampp\htdocs\travel_daklak\main\includes\lang_en.php', $en_add);
echo "Added missing translations!\n";
